import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import stylistic from "@stylistic/eslint-plugin";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended, // optional unless you're using "eslint:recommended" https://github.com/eslint/eslintrc#usage
});

const eslintConfig = [
  ...compat.extends("eslint:recommended", "next/core-web-vitals", "next/typescript"),
  stylistic.configs.customize({
    // the following options are the default values
    indent: 2,
    quotes: "double",
    semi: true,
    jsx: true,
    arrowParens: true,
  }),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "sanity/sanity.types.ts", // Auto-generated by Sanity TypeGen by another sanity studio repo
    ],
  },
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"],
    rules: {
      "@stylistic/multiline-ternary": ["error", "always-multiline", { ignoreJSX: true }],
    },
  },
];

export default eslintConfig;
