import js from "@eslint/js";
import stylistic from "@stylistic/eslint-plugin";
import next from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = [
  js.configs.recommended,
  ...next,
  ...nextTs,
  stylistic.configs.customize({
    // the following options are the default values
    indent: 2,
    quotes: "double",
    semi: true,
    jsx: true,
    arrowParens: true,
  }),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "sanity/sanity.types.ts", // Auto-generated by Sanity TypeGen by another sanity studio repo
    ],
  },
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"],
    rules: {
      "@stylistic/multiline-ternary": ["error", "always-multiline", { ignoreJSX: true }],
    },
  },
];

export default eslintConfig;
