/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Whichday = 1 | 2 | 3 | 4 | 5 | 6 | 7

export type TimeValue =
  | '08:00'
  | '08:10'
  | '08:20'
  | '08:30'
  | '08:40'
  | '08:50'
  | '09:00'
  | '09:10'
  | '09:20'
  | '09:30'
  | '09:40'
  | '09:50'
  | '10:00'
  | '10:10'
  | '10:20'
  | '10:30'
  | '10:40'
  | '10:50'
  | '11:00'
  | '11:10'
  | '11:20'
  | '11:30'
  | '11:40'
  | '11:50'
  | '12:00'
  | '12:10'
  | '12:20'
  | '12:30'
  | '12:40'
  | '12:50'
  | '13:00'
  | '13:10'
  | '13:20'
  | '13:30'
  | '13:40'
  | '13:50'
  | '14:00'
  | '14:10'
  | '14:20'
  | '14:30'
  | '14:40'
  | '14:50'
  | '15:00'
  | '15:10'
  | '15:20'
  | '15:30'
  | '15:40'
  | '15:50'
  | '16:00'
  | '16:10'
  | '16:20'
  | '16:30'
  | '16:40'
  | '16:50'
  | '17:00'
  | '17:10'
  | '17:20'
  | '17:30'
  | '17:40'
  | '17:50'
  | '18:00'
  | '18:10'
  | '18:20'
  | '18:30'
  | '18:40'
  | '18:50'
  | '19:00'
  | '19:10'
  | '19:20'
  | '19:30'
  | '19:40'
  | '19:50'
  | '20:00'
  | '20:10'
  | '20:20'
  | '20:30'
  | '20:40'
  | '20:50'
  | '21:00'
  | '21:10'
  | '21:20'
  | '21:30'
  | '21:40'
  | '21:50'
  | '22:00'
  | '22:10'
  | '22:20'
  | '22:30'
  | '22:40'
  | '22:50'
  | '23:00'
  | '23:10'
  | '23:20'
  | '23:30'
  | '23:40'
  | '23:50'

export type Tag = {
  _type: 'tag'
  name?: string
  nameCN?: string
}

export type Schedule = {
  _type: 'schedule'
  whichday?: Whichday
  timeDuration?: TimeDuration
}

export type TimeDuration = {
  _type: 'timeDuration'
  startTime?: TimeValue
  endTime?: TimeValue
}

export type Class = {
  _id: string
  _type: 'class'
  _createdAt: string
  _updatedAt: string
  _rev: string
  sequence?: number
  title?: string
  titleCN?: string
  level?: 'beginner' | 'intermediate' | 'advanced'
  instructor?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'instructor'
  }
  capacity?: number
  description?: string
  descriptionCN?: string
  schedule?: Array<
    {
      _key: string
    } & Schedule
  >
  tags?: Array<
    {
      _key: string
    } & Tag
  >
}

export type Instructor = {
  _id: string
  _type: 'instructor'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  bio?: string
  photo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Address = {
  _id: string
  _type: 'address'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  streetNumber?: string
  streetName?: string
  suburb?: string
  city?: string
  postcode?: string
  country?: string
  addressCN?: string
  cityCN?: string
  countryCN?: string
  phone?: string
  email?: string
}

export type NavItems = Array<
  {
    _key: string
  } & ButtonContent
>

export type NavBar = {
  _id: string
  _type: 'navBar'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  logo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  siteName?: string
  siteName2?: string
  navItems?: NavItems
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  pageTitle?: Array<
    {
      _key: string
    } & TitleSentence
  >
  button1Red?: ButtonContent
  button2White?: ButtonContent
}

export type ButtonContent = {
  _type: 'buttonContent'
  name?: string
  nameCN?: string
  url?: string
}

export type TitleSentence = {
  _type: 'titleSentence'
  title?: Sentence
  titleCN?: Sentence
}

export type Sentence = {
  _type: 'sentence'
  sentence?: string
  stressWord?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | Whichday
  | TimeValue
  | Tag
  | Schedule
  | TimeDuration
  | Class
  | Instructor
  | Address
  | NavItems
  | NavBar
  | HomePage
  | ButtonContent
  | TitleSentence
  | Sentence
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
